class BibleBooks

  def last_chapter(book)
    CHAPTER_COUNT[book.downcase.to_sym]
  end

  def next_book(book)
    BOOK_PROGRESSION[book.downcase.to_sym]
  end

  BOOK_PROGRESSION = {
    matthew: 'Mark',
    mark: 'Luke',
    luke: 'John',
    john: 'Matthew',
    genesis: 'Exodus',
    exodus: 'Leviticus',
    leviticus: 'Numbers',
    numbers: 'Deuteronomy',
    deuteronomy: 'Genesis',
    romans: '1 Corinthians',
    first_corinthians: '2 Corinthians',
    second_corinthians: 'Galatians',
    galatians: 'Ephesians',
    ephesians: 'Philippians',
    philippians: 'Colossians',
    colossians: 'Hebrews',
    hebrews: 'Romans',
    first_thessalonians: '2 Thessalonians',
    second_thessalonians: '1 Timothy',
    first_timothy: '2 Timothy',
    second_timothy: 'Titus',
    titus: 'Philemon',
    philemon: 'James',
    james: '1 Peter',
    first_peter: '2 Peter',
    second_peter: '1 John',
    first_john: '2 John',
    second_john: '3 John',
    third_john: 'Jude',
    jude: 'Revelation',
    revelation: '1 Thessalonians',
    job: 'Ecclesiastes',
    ecclesiastes: 'Song of Solomon',
    song_of_solomon: 'Job',
    psalms: 'Psalms',
    proverbs: 'Proverbs',
    joshua: 'Judges',
    judges: 'Ruth',
    ruth: '1 Samuel',
    first_samuel: '2 Samuel',
    second_samuel: '1 Kings',
    first_kings: '2 Kings',
    second_kings: '1 Chronicles',
    first_chronicles: '2 Chronicles',
    second_chronicles: 'Ezra',
    ezra: 'Nehemiah',
    nehemiah: 'Esther',
    esther: 'Joshua',
    isaiah: 'Jeremiah',
    jeremiah: 'Lamentations',
    lamentations: 'Ezekiel',
    ezekiel: 'Daniel',
    daniel: 'Hosea',
    hosea: 'Joel',
    joel: 'Amos',
    amos: 'Obadiah',
    obadiah: 'Jonah',
    jonah: 'Micah',
    micah: 'Nahum',
    nahum: 'Habakkuk',
    habakkuk: 'Zephaniah',
    zephaniah: 'Haggai',
    haggai: 'Zechariah',
    zechariah: 'Malachi',
    malachi: 'Isaiah',
    acts: 'Acts'
  }

  CHAPTER_COUNT = {
    genesis: 50,
    exodus: 40,
    leviticus: 27,
    numbers: 36,
    deuteronomy: 34,
    joshua: 24,
    judges: 21,
    ruth: 4,
    first_samuel: 31,
    second_samuel:24,
    first_kings: 22,
    second_kings: 25,
    first_chronicles: 29,
    second_chronicles: 36,
    ezra: 10,
    nehemiah: 13,
    esther: 10,
    job: 42,
    psalms: 150,
    proverbs: 31,
    ecclesiastes: 12,
    song_of_solomon: 8,
    isaiah: 66,
    jeremiah: 52,
    lamentations: 5,
    ezekiel: 48,
    daniel: 12,
    hosea: 14,
    joel: 3,
    amos: 9,
    obadiah: 1,
    jonah: 4,
    micah: 7,
    nahum: 3,
    habakkuk: 3,
    zephaniah: 3,
    haggai: 2,
    zechariah: 14,
    malachi: 4,
    matthew: 28,
    mark: 16,
    luke: 24,
    john: 21,
    acts: 28,
    romans: 16,
    first_corinthians: 16,
    second_corinthians: 13,
    galatians: 6,
    ephesians: 6,
    philippians: 4,
    colossians: 4,
    first_thessalonians: 5,
    second_thessalonians: 3,
    first_timothy: 6,
    second_timothy: 4,
    titus: 3,
    philemon: 1,
    hebrews: 13,
    james: 5,
    first_peter: 5,
    second_peter: 3,
    first_john: 5,
    second_john: 1,
    third_john: 1,
    jude: 1,
    revelation: 22
  }
end


